include:
  - base.yml
# Local環境以外では埋め込まないこと（セキュリティ）
# 
settings:
  API_URL: http://localhost:8080
  API_KEY: 1f765fc8-05b2-b4a4-b290-0416ede7e712
targets:
  MobileNovelReader:
    info:
      properties:
        API_URL: ${API_URL}
        API_KEY: ${API_KEY}
